ServerlessDeploymentBucketName: ${cf:initialize-serverless-${self:provider.stage}.ServerlessDeploymentBucketName}

CloudFormationStackRoleArn: ${cf:initialize-serverless-${self:provider.stage}.CloudFormationStackRoleArn}
