# Cross-CloudFormation stack references
CloudFormationStackRoleArn: ${cf:initialize-serverless-${self:provider.stage}.CloudFormationStackRoleArn}
ServerlessDeploymentBucketName: ${cf:initialize-serverless-${self:provider.stage}.ServerlessDeploymentBucketName}
