service: serverless-javascript-boilerplate

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${file(${self:custom.config.${self:provider.stage}}):ServerlessDeploymentBucketName}
    maxPreviousDeploymentArtifacts: 1
  role: !GetAtt SharedLambdaFunctionRole.Arn
  cfnRole: ${file(${self:custom.config.${self:provider.stage}}):CloudFormationStackRoleArn}
  versionFunctions: false

package:
  individually: true

functions:
  FooBarLambdaFunction: ${file(./sls/lambda/FooBarLambdaFunction.yml)}
  HelloWorldLambdaFunction: ${file(./sls/lambda/HelloWorldLambdaFunction.yml)}

resources:
  Description: CloudFormation stack for ${self:service}-${self:provider.region}-${self:provider.stage}
  Resources:
    ReadS3Policy: ${file(./sls/iam/ReadS3Policy.yml)}
    SharedLambdaFunctionRole: ${file(./sls/iam/SharedLambdaFunctionRole.yml)}
  Outputs:
    SharedLambdaFunctionRoleArn:
      Description: Lambda function role generated by the template
      Value: !GetAtt SharedLambdaFunctionRole.Arn

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    lambdaPort: 8180
    httpPort: 8080
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
  config:
    local: ./serverless.config.dev.yml
    dev: ./serverless.config.prd.yml
