# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build.yml
      - res/**/sls/*.yml
      - res/**/serverless.config.*.yml
      - res/**/serverless.yml
      - sls/**/*.yml
      - src/**/*.js
      - .cfnlintrc
      - gulpfile.js
      - package-lock.json
      - package.json
      - serverless.config.*.yml
      - serverless.yml
      - webpack.config.js
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/build.yml
      - res/**/sls/*.yml
      - res/**/serverless.config.*.yml
      - res/**/serverless.yml
      - sls/**/*.yml
      - src/**/*.js
      - .cfnlintrc
      - gulpfile.js
      - package-lock.json
      - package.json
      - serverless.config.*.yml
      - serverless.yml
      - webpack.config.js

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        serverless-version: [2.x]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    #########################################
    ## Installation
    - name: Use Node.js (v${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use Serverless CLI (v${{ matrix.serverless-version }})
      run: |
        npm install serverless@${{ matrix.serverless-version }} --global
        npm install webpack --global

    - name: Perform clean install
      run: npm ci

    #########################################
    ## Generate the serverless artifacts
    - name: Generate initialize-serverless CloudFormation template
      run: |
        cd ./res/initialize-serverless
        sls package --stage dev

    - name: Generate deployment CloudFormation template
      run: sls package --stage local

    #########################################
    ## Lint generated CloudFormation template
    - name: Execute cfn-lint using .cfnlintrc
      uses: scottbrenner/cfn-lint-action@master
