# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Quality Check

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/quality-check.yml
      - src/**/*.js
      - test/**/*.js
      - .eslintrc.json
      - .mocharc.json
      - .nycrc.json
      - package-lock.json
      - package.json
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/quality-check.yml
      - src/**/*.js
      - test/**/*.js
      - .eslintrc.json
      - .mocharc.json
      - .nycrc.json
      - package-lock.json
      - package.json
  schedule:
    # At 2:00 PM UTC on Sunday
    - cron: '0 14 * * 0'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    #########################################
    ## Installation
    - name: Use Node.js (v${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Perform clean install
      run: npm ci

    #########################################
    ## Built-in Quality Checks
    - name: Execute unit tests
      run: npm test

    - name: Execute code quality rules
      run: npm run lint

    #########################################
    ## Code Scanning using CodeQL
    - name: Initialize CodeQL tools for scanning
      uses: github/codeql-action/init@v1
      with:
        languages: ['javascript']

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v1
